### ISSUE TITLE
Wyrenderowana wersja przetłumaczonej książki on-line

### ISSUE THREAD

**Issue by beling** [beling/book-pl#18]
Tu można zobaczyć jak wygląda wyrenderowana wersja przetłumaczonej książki:
http://rust.w8.pl/book/
Co jakiś czas będę tę stronę aktualizował.

**Comment by katecpp** [comment]
Dałoby się dodać jakiś tag do strony z datą kiedy została wyrenderowana?

**Comment by beling** [comment]
Na razie wrzucam ręcznie, ale jak napiszę jakiś skrypt to oczywiście nie będzie problemu.
Raczej informacje będzie na stronie http://rust.w8.pl/ niż w samej książce.

**Comment by beling** [comment]
OK, zrobione. Wyświetlana jest data modyfikacji pliku index.html książki.
