### ISSUE TITLE
Transfer repozytorium

### ISSUE THREAD

**Issue by paytchoo** [beling/book-pl#19]
Zycie potoczylo sie tak, a nie inaczej. Po dlugim czasie nieaktywnosci postanowilem przekazac wlasnosc repozytorium komus z Was. Ktos jest chetny?

**Comment by JakubKoralewski** [comment]
@beling ?

**Comment by beling** [comment]
Dobra. Nie znam procedury. Czy ja muszę coś tu kliknąć?

**Comment by JakubKoralewski** [comment]
Pewnie będziesz musiał tylko kliknąć OK

**Comment by paytchoo** [comment]
To chyba jednak nie takie proste. GitHub nie pozwala na transfer, jesli u docelowego uzytkownika istnieje juz fork. Forka nie mozna "uniezaleznic". chyba, ze tworzac nowe repozytorium.

**Comment by beling** [comment]
Żaden problem. Skasowałem ten fork.
