### ISSUE TITLE
"Kompilacje" listingów w wersji 2015 zamiast 2018

### ISSUE THREAD

**Issue by stepaluch** [beling/book-pl#22]
Hejo

We wstępie książki jest napisane '...używasz wersji Rusta 1.49 lub nowszej, z wyrażeniem edition="2018"...' tymczasem skrypt który "kompiluje" listingi (https://play.rust-lang.org/evaluate.json) w POST otrzymuje parametr o wersji 2015 np:
`
{"version":"stable","optimize":"0","code":"fn main() {\n    println!(\"Witaj, świecie!\");\n}\n","edition":"2015"}
`

wygląda na to że w 'book.toml' trzeba dodać:

`[rust]`
`edition = "2018"`

https://rust-lang.github.io/mdBook/format/config.html

**Comment by beling** [comment]
My synchronizujemy wszelkie skrypty z https://github.com/rust-lang/book i sami ich nie zmieniamy. Jeżeli sprawa jest aktualna i w skryptach są jakiekolwiek błędy, to proszę o zgłaszanie ich na https://github.com/rust-lang/book
