### ISSUE TITLE
Strona domyślna repozytorium

### ISSUE THREAD

**Issue by katecpp** [beling/book-pl#3]
Zastanawiam się nad domyślną stroną naszego repo - czyli dokładnie tym: https://github.com/paytchoo/book-pl . Jest tam obecnie instrukcja budowania książki. Czy po "resecie" repo dalej mamy możliwość budowania mdbook? (Nie sprawdzałam - nie chce mi się instalować tooli). Czy ktoś z Was używa tego budowania lub planuje używać? Jeśli nie, to można by zastąpić tę stronę kopią spisu treści, czyli tym: https://github.com/paytchoo/book-pl/blob/master/src/SUMMARY.md (zostawiając ewentualnie pierwszy akapit aktualnej strony)

To luźne przemyślenie i jeśli ktokolwiek uważa że budowanie mdbook się przyda to nie upieram się.

**Comment by paytchoo** [comment]
Ktoś kiedyś wspominał na forum w repo oryginału, że w przyszłości mdbook ma obsługiwać treści wielojęzyczne. Zakładałem, że tłumaczenie nie zmieni innych aspektów książki, w tym możliwości korzystania z mdbook. W obecnym stanie powinna się wciąż dać zbudować, chociaż też nie próbowałem.

**Comment by katecpp** [comment]
Ok z racji że nic mądrego nie wymyśliłam to zamykam ten ticket; zostajemy przy tym co jest. :)
